services:
  back:
    build:
      context: ./backend/memeback
      dockerfile: ./backend/memeback/Dockerfile
    networks:
      - main

  front:
    build:
      context: ./frontend/my-gallery-app
      dockerfile: ./frontend/my-gallery-app/Dockerfile
    networks:
      - main

  cloudflare:
    image: docker.io/postgres:18
    networks:
      - main

networks:
  main:
    driver: bridge